const countryCodes = [
  { code: "World", name: "World", code3: "WLD" },
  { code: "US", name: "United States", code3: "USA" },
  { code: "CN", name: "China", code3: "CHN" },
  { code: "RU", name: "Russia", code3: "RUS" },
  { code: "IN", name: "India", code3: "IND" },
  { code: "ID", name: "Indonesia", code3: "IDN" },
  { code: "BR", name: "Brazil", code3: "BRA" },
  { code: "PK", name: "Pakistan", code3: "PAK" },
  { code: "NG", name: "Nigeria", code3: "NGA" },
  { code: "BD", name: "Bangladesh", code3: "BGD" },
  { code: "MX", name: "Mexico", code3: "MEX" },
  { code: "JP", name: "Japan", code3: "JPN" },
  { code: "DE", name: "Germany", code3: "DEU" },
  { code: "FR", name: "France", code3: "FRA" },
  { code: "GB", name: "United Kingdom", code3: "GBR" },
  { code: "IT", name: "Italy", code3: "ITA" },
  { code: "ZA", name: "South Africa", code3: "ZAF" },
  { code: "CA", name: "Canada", code3: "CAN" },
  { code: "AU", name: "Australia", code3: "AUS" },
  { code: "AR", name: "Argentina", code3: "ARG" },
  { code: "SA", name: "Saudi Arabia", code3: "SAU" },
  { code: "EG", name: "Egypt", code3: "EGY" },
  { code: "TR", name: "Turkey", code3: "TUR" },
  { code: "IR", name: "Iran", code3: "IRN" },
  { code: "TH", name: "Thailand", code3: "THA" },
  { code: "KR", name: "South Korea", code3: "KOR" },
  { code: "VN", name: "Vietnam", code3: "VNM" },
  { code: "MY", name: "Malaysia", code3: "MYS" },
  { code: "PH", name: "Philippines", code3: "PHL" },
  { code: "PL", name: "Poland", code3: "POL" },
  { code: "UA", name: "Ukraine", code3: "UKR" },
  { code: "ES", name: "Spain", code3: "ESP" },
  { code: "GR", name: "Greece", code3: "GRC" },
  { code: "CH", name: "Switzerland", code3: "CHE" },
  { code: "SE", name: "Sweden", code3: "SWE" },
  { code: "AT", name: "Austria", code3: "AUT" },
  { code: "CZ", name: "Czech Republic", code3: "CZE" },
  { code: "HU", name: "Hungary", code3: "HUN" },
  { code: "PT", name: "Portugal", code3: "PRT" },
  { code: "RO", name: "Romania", code3: "ROU" },
  { code: "DK", name: "Denmark", code3: "DNK" },
  { code: "FI", name: "Finland", code3: "FIN" },
  { code: "NO", name: "Norway", code3: "NOR" },
  { code: "IE", name: "Ireland", code3: "IRL" },
  { code: "NZ", name: "New Zealand", code3: "NZL" },
  { code: "SG", name: "Singapore", code3: "SGP" }
];

export { countryCodes };
